"""
Generate docs/data_bundle.js — embeds all processed data as a JS global
so that the HTML pages work when opened directly from the file system
(file:// protocol) without an HTTP server.

Usage:  python scripts/bundle_data.py
Output: docs/data_bundle.js  (~16 MB, minified JSON)
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
PROCESSED = ROOT / "data" / "processed"
OUT = ROOT / "docs" / "data_bundle.js"

# Map: key used in DATA_BUNDLE → filename in data/processed/
# Keys match the paths used in the HTML PATHS objects
FILES = {
    "../data/processed/its_results.json":           "its_results.json",
    "../data/processed/monitor_stations.geojson":   "monitor_stations.geojson",
    "../data/processed/crz_boundary.geojson":       "crz_boundary.geojson",
    "../data/processed/dac_tracts_nyc.geojson":     "dac_tracts_nyc.geojson",
    "../data/processed/traffic_diversion.json":     "traffic_diversion.json",
    "../data/processed/crz_daily.json":             "crz_daily.json",
    "../data/processed/nyccas_raster_points.geojson": "nyccas_raster_points.geojson",
    "../data/processed/headline_stats.json":        "headline_stats.json",
    "../data/processed/bt_facilities.geojson":      "bt_facilities.geojson",
    "../data/processed/canyon_analysis.json":       "canyon_analysis.json",
    "../data/processed/corridor_trees.geojson":     "corridor_trees.geojson",
    "../data/processed/corridor_buildings.geojson": "corridor_buildings.geojson",
    "../data/processed/corridor_streets.geojson":   "corridor_streets.geojson",
    "../data/processed/corridor_meta.json":         "corridor_meta.json",
    "../data/processed/school_zone.json":          "school_zone.json",
    "../data/processed/robustness.json":           "robustness.json",
}

def main():
    bundle = {}
    total = 0
    for path_key, filename in FILES.items():
        fpath = PROCESSED / filename
        if not fpath.exists():
            print(f"  SKIP (not found): {filename}")
            continue
        raw = fpath.read_text(encoding="utf-8")
        size_kb = len(raw) / 1024
        total += size_kb
        print(f"  {filename:45s}  {size_kb:7.1f} KB")
        bundle[path_key] = json.loads(raw)

    print(f"\n  Total: {total/1024:.1f} MB across {len(bundle)} files")

    # Write JS — JSON.stringify is minified (separators=(',',':'))
    js_lines = ["// Auto-generated by scripts/bundle_data.py — do not edit manually",
                "// Allows HTML pages to open directly from the file system without a server.",
                "window.DATA_BUNDLE = {"]
    keys = list(bundle.keys())
    for i, k in enumerate(keys):
        comma = "," if i < len(keys) - 1 else ""
        serialised = json.dumps(bundle[k], separators=(',', ':'), ensure_ascii=False)
        js_lines.append(f'  {json.dumps(k)}: {serialised}{comma}')
    js_lines.append("};")

    OUT.write_text("\n".join(js_lines), encoding="utf-8")
    out_kb = OUT.stat().st_size / 1024
    print(f"\nWrote {OUT.name}  ({out_kb/1024:.1f} MB)")

if __name__ == "__main__":
    main()
